# Generated by Django 5.0.2 on 2024-02-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('no_started', 'Not Started'), ('continues', 'Continues'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='no_started', max_length=20),
        ),
    ]
