# Generated by Django 5.0.2 on 2024-02-24 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_student_status'),
        ('group', '0002_alter_group_mentor_alter_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='group.group'),
        ),
    ]
