# Generated by Django 5.0.2 on 2024-02-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='coming',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
