# Generated by Django 5.0.2 on 2024-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_mentor_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
