# Generated by Django 5.0.2 on 2024-04-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_student_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grant',
            field=models.BooleanField(default=False),
        ),
    ]
