# Generated by Django 4.2.14 on 2024-07-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_student_grant'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(upload_to='student/excel/')),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-update_time'],
            },
        ),
    ]
