# Generated by Django 4.2.14 on 2024-07-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_studentsexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsExcel',
        ),
    ]
