# Generated by Django 5.0.2 on 2024-02-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
