# Generated by Django 5.0.2 on 2024-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='val',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
