# Generated by Django 5.0.2 on 2024-02-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('plastic', 'Plastic'), ('bank', 'Bank')], default=('cash', 'Cash'), max_length=10)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.student')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
