# Generated by Django 5.0.2 on 2024-02-24 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('plastic', 'Plastic'), ('bank', 'Bank')], default='cash', max_length=10),
        ),
    ]
