# Generated by Django 5.0.2 on 2024-03-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(default='1-oy', max_length=20),
        ),
    ]
