# Generated by Django 5.0.2 on 2024-02-23 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group/images/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('started_time', models.DateTimeField(blank=True, null=True)),
                ('finished_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('no_started', 'Not Started'), ('continues', 'Continues'), ('completed', 'Completed'), ('deleted', 'Deleted')], default=('no_started', 'Not Started'), max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='course.course')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='customer.mentor')),
            ],
            options={
                'ordering': ['title', 'course'],
            },
        ),
    ]
