# Generated by Django 5.0.2 on 2024-02-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_student_status'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='customer.mentor'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('no_started', 'Not Started'), ('continues', 'Continues'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='no_started', max_length=20),
        ),
    ]
