# Generated by Django 5.0.2 on 2024-03-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_mentor_alter_group_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='study_day',
            field=models.CharField(choices=[('toq', 'Dushanba, Chorshanba, Juma'), ('juft', 'Seshanba, Payshanba, Shanba')], default='toq', max_length=50),
        ),
    ]
