# Generated by Django 5.0.2 on 2024-03-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_group_study_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='continuity',
            field=models.IntegerField(default=6),
        ),
    ]
