# Generated by Django 5.0.2 on 2024-03-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_group_continuity'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='lesson_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lesson_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
