# Generated by Django 5.0.2 on 2024-04-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_lesson_end_time_group_lesson_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='added_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
