# Generated by Django 5.0.6 on 2024-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='study_day',
            field=models.CharField(choices=[('toq', 'Dushanba, Chorshanba, Juma'), ('juft', 'Seshanba, Payshanba, Shanba'), ('barcha_kun', 'Har kuni')], default='toq', max_length=50),
        ),
    ]
