# Generated by Django 5.0.2 on 2024-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lid_app', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='lid',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
